### ISSUE TITLE
[video_player] Platform Exception happens when playing multiple videos 

### ISSUE THREAD

**Issue by ynoo-nam** [flutter-tizen/plugins#135]
I keep disposing of, creating, and initializing the VideoPlayerControllers to play multiple videos successively.
The below error happens while initializing a new video.

I usually dispose of the current controller then create and init new controller under the below condition. (in listener())
I am kind of sure it is not because of using disposed VideoPlayerController because the Error Log is different,
but not sure if my implementation affects it or not.

```
      _onComplete = () {
        if (_controller.value.isInitialized &&
            !_controller.value.isPlaying &&
            (_controller.value.duration == _controller.value.position)) {
          listener();
          if (_onComplete != null) {
            _controller.removeListener(_onComplete!);
            _onComplete = null;
          }
        }
      };
      _controller.addListener(_onComplete!);
```

```
E/ConsoleMessage( 5849): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(player_prepare_async failed, Function not implemented, null, null)
#0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:189:7)
<asynchronous suspension>
#1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:47:31)
<asynchronous suspension>
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:308:19)
<asynchronous suspension>
#3      VideoManager._initPlay (package:test_video/main.dart:241:5)
<asynchronous suspension>
#4      VideoManager.play (package:test_video/main.dart:216:5)
<asynchronous suspension>

E/ConsoleMessage( 5849): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(player_get_play_position failed, Function not implemented, null, null)
#0      VideoPlayerApi.position (package:video_player_platform_interface/messages.dart:340:7)
<asynchronous suspension>
#1      MethodChannelVideoPlayer.getPosition (package:video_player_platform_interface/method_channel_video_player.dart:94:9)
<asynchronous suspension>
#2      VideoPlayerController.position (package:video_player/video_player.dart:477:12)
<asynchronous suspension>
#3      VideoPlayerController._applyPlayPause.<anonymous closure> (package:video_player/video_player.dart:431:41)
<asynchronous suspension>
```

```
E/ConsoleMessage( 3948): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(player_pause failed, Function not implemented, null, null)
#0      VideoPlayerApi.pause (package:video_player_platform_interface/messages.dart:390:7)
<asynchronous suspension>
#1      VideoPlayerController._applyPlayPause (package:video_player/video_player.dart:445:7)
<asynchronous suspension>
#2      VideoPlayerController.pause (package:video_player/video_player.dart:406:5)
<asynchronous suspension>
```

flutter-tizen doctor -v
```
[✓] Flutter (Channel unknown, 2.0.1, on Linux, locale ko_KR.UTF-8)
    • Flutter version 2.0.1 at /home/yeonwoo/flutter_tizen/flutter-tizen/flutter
    • Framework revision c5a4b4029c (4달 전), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/yeonwoo/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Tizen toolchain - develop for Tizen devices
    • Tizen Studio 4.1 at /home/yeonwoo/tizen-studio
    • .NET CLI executable at /snap/bin/dotnet

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

• No issues found!

```

**Comment by swift-kim** [comment]
@ynoo-nam Could you provide a cleaner example (complete app) to reproduce the error?

cc @xuelian-bai @xiaowei-guan @XuWanchaoS

**Comment by XuWanchaoS** [comment]
The test sample is https://github.sec.samsung.net/ynoo-nam/video_example. This issue is tested on tizen emulator on platform mobile-6.0-x86. The issue is ususally (maybe not always) reproduced when you click the second or third button, which plays the private videos.
And this https://github.sec.samsung.net/f-project/servingbot-app/tree/test is the real app that needs to use the video_player plugin.
I will check this issue.

**Comment by swift-kim** [comment]
@XuWanchaoS said,

> The test sample is https://github.sec.samsung.net/ynoo-nam/video_example. This issue is tested on tizen emulator on platform mobile-6.0-x86. The issue is ususally (maybe not always) reproduced when you click the second or third button, which plays the private videos.

**Comment by XuWanchaoS** [comment]
The video_player plugin use mmplayer interface on tizen, and mmplayer use muse-server (that running via systemd). muse-server has memory limit (/usr/lib/system/systemd/muse-server.service), so if mulitiple video players are running at the same time, out of memory may be occurred and the mmplayer api will throw error "Function not implemented".

```
    Future.delayed(Duration(seconds: 3), () {
      controllerCnt--;
      if (old.value.isInitialized) initCnt--;
      old.dispose();
      Log.log(
          'disposed $id ${old.dataSource} controllerCnt: $controllerCnt initedControllerCnt: $initCnt');
    });
```

In the test sample, the old VideoPlayerController should be kept until VideoPlayer is rebuilt. The old VideoPlayerController is delayed to dispose. So more than one vide player are running. If the count of video_palyer is more than three, this error is occurred on tizen emulator mobile-6.0-x86.

It's better to dispose VideoPlayerController without delay. Here is my solution.
1. Modify the _VideoPlayerState of  video_player plugin.
```
  @override
  void didUpdateWidget(VideoPlayer oldWidget) {
    super.didUpdateWidget(oldWidget);
    oldWidget.controller.removeListener(_listener);
    _textureId = widget.controller.textureId;
    widget.controller.addListener(_listener);
  }
```
Remove code 'oldWidget.controller.removeListener(_listener);', you can dispose VideoPlayerController without delay.

2. Destroy VideoPlayer widget when use setState to update view.
Here is my sample
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: _ButterFlyAssetVideo(),
      ),
    ),
  );
}

typedef OnCompleted = void Function();

class VideoManager with ChangeNotifier {
  VideoPlayerController? _controller;
  VideoPlayerController? get controller => _controller;

  bool _isInitialized = false;
  bool get isInitialized => _isInitialized;

  void playVideos(List<String> videos, {OnCompleted? onComplete}) {
    assert(videos.isNotEmpty);
    _playVideos(videos, onComplete, 0);
  }

  void _playVideos(List<String> videos, OnCompleted? onComplete, int index) {
    if (videos.length - 1 == index) {
      _play(videos[index], onComplete: onComplete);
    } else {
      _play(videos[index], onComplete: () =>
          _playVideos(videos, onComplete, index + 1));
    }
  }

  void play(String src, {bool looping = false, OnCompleted? onComplete}) {
    _play(src, onComplete: onComplete);
  }

  void _play(String src, {bool looping = false, OnCompleted? onComplete}) {
    _controller?.dispose();
    _controller = VideoPlayerController.asset(src);
    _isInitialized = false;
    notifyListeners();

    _controller!.initialize().then((value) {
      _isInitialized = true;
      notifyListeners();
    });
    _controller!.setLooping(looping);
    _controller!.play();

    _controller!.addListener(() {
      if (_controller!.value.hasError) {
        print(_controller!.value.errorDescription);
      }

      bool complete = _controller!.value.isInitialized &&
          !_controller!.value.isPlaying &&
          _controller!.value.duration == _controller!.value.position;
      if (complete && onComplete != null) {
        onComplete();
      }
    });
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }
}

class Videos {
  static const String dir = "assets/videos/";
  static const String basic = "basic.mp4";
  static const String basic02 = "basic_02.mp4";
  static const String circleToFacial = "circle_to_facial.mp4";
  static const String circleToIndicator = "circle_to_indicator.mp4";
  static const String circleToWorking = "circle_to_working.mp4";
  static const String engaged = "engaged.mp4";
  static const String facialToCircle = "facial_to_circle.mp4";
  static const String goodbye = "goodbye.mp4";
  static const String greeting = "greeting.mp4";
  static const String happy = "happy.mp4";
  static const String idle01 = "idle_01.mp4";
  static const String idle02 = "idle_02.mp4";
  static const String idle03 = "idle_03.mp4";
  static const String indicatorToCircle = "indicator_to_circle.mp4";
  static const String patrol01 = "patrol_01.mp4";
  static const String shy = "shy.mp4";
  static const String working = "working.mp4";
  static const String workingToCircle = "working_to_circle.mp4";
  static const String wow = "wow.mp4";

  static List<String> toList() => _lists;
  static const List<String> _lists = [
    Videos.idle01,
    Videos.idle02,
    Videos.idle03,
    Videos.basic,
    Videos.basic02,
    Videos.indicatorToCircle,
    Videos.circleToIndicator,
    Videos.facialToCircle,
    Videos.circleToFacial,
    Videos.workingToCircle,
    Videos.circleToWorking,
    Videos.happy,
    Videos.shy,
    Videos.wow,
    Videos.working,
    Videos.patrol01,
    Videos.engaged,
    Videos.goodbye,
    Videos.greeting,
  ];
}

class _ButterFlyAssetVideo extends StatefulWidget {
  @override
  _ButterFlyAssetVideoState createState() => _ButterFlyAssetVideoState();
}

class _ButterFlyAssetVideoState extends State<_ButterFlyAssetVideo> {
  late VideoPlayerController _controller;
  bool _isInitialized = false;
  VideoManager _videoManager = VideoManager();
  var list = Videos.toList();

  @override
  void initState() {
    super.initState();
    _videoManager.addListener(() {
      setState(() {
        _isInitialized = _videoManager.isInitialized;
        _controller = _videoManager.controller!;
      });
    });

    _videoManager.play('assets/Butterfly-209.mp4');
    _controller = _videoManager._controller!;
  }

  @override
  void dispose() {
    _videoManager.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(
            padding: const EdgeInsets.only(top: 20.0),
          ),
          const Text('With assets mp4'),
          Container(
            width: 500,
            height: 200,
            padding: const EdgeInsets.all(20),
            child: Stack(
              alignment: Alignment.bottomCenter,
              children: <Widget>[
                if (_isInitialized) VideoPlayer(_controller),
              ],
            ),
          ),
          OutlinedButton(
            child: Text('play butterfly 12 times'),
            onPressed: () {
              var list = List.generate(12, (index) => 'assets/Butterfly-209.mp4');
              _videoManager.playVideos(list);
            },
          ),
          OutlinedButton(
            child: Text('play bot videos 12 times'),
            onPressed: () {
              var _list = List.generate(12, (index) => Videos.dir + list[index]);
              _videoManager.playVideos(_list);
            },
          ),
          OutlinedButton(
            child: Text('play a bot video 12 times'),
            onPressed: () {
              var _list = List.generate(12, (index) => Videos.dir + list[0]);
              _videoManager.playVideos(_list);
            },
          ),
        ],
      ),
    );
  }
}
```

**Comment by swift-kim** [comment]
Is this still an active issue?

**Comment by ynoo-nam** [comment]
> Is this still an active issue?

The answer wasn't the solution for this issue.
Anyway, it seems like this issue isn't reproduced at the moment.
I'll close it for now.
