### ISSUE TITLE
[audioplayers] Failing integration test in tv-6.0 emulator

### ISSUE THREAD

**Issue by HakkyuKim** [flutter-tizen/plugins#239]
@XuWanchaoS 
Integration test is failing on tv-6.0 emulator, could you take a look?

```
./tools/run_command.py test --plugins audioplayers --use-ephemeral-targets --platforms wearable-5.5 tv-6.0
...
============= TEST RESULT =============
SUCCEEDED: audioplayers ('wearable-5.5', 'wearable-5_5-641394', None)
FAILED: audioplayers ('tv-6.0', 'tv-6_0-641394', None)
flutter-tizen test integration_test failed, see the output above for details.
Some tests failed.
```

The error message is:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: AudioPlayerState:<AudioPlayerState.COMPLETED>
Actual: AudioPlayerState:<AudioPlayerState.PLAYING>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/hakkyu/mydir/project/flutter-project/plugins/packages/audioplayers/example/integration_test/audioplayers_test.dart:122:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...

This was caught by the test expectation on the following line:
file:///home/hakkyu/mydir/project/flutter-project/plugins/packages/audioplayers/example/integration_test/audioplayers_test.dart line 122
The test description was:
do not exceed duration after audio completed
════════════════════════════════════════════════════════════════════════════════════════════════════
(If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: AudioPlayerState:<AudioPlayerState.COMPLETED>
Actual: AudioPlayerState:<AudioPlayerState.PLAYING>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/hakkyu/mydir/project/flutter-project/plugins/packages/audioplayers/example/integration_test/audioplayers_test.dart:122:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...

This was caught by the test expectation on the following line:
file:///home/hakkyu/mydir/project/flutter-project/plugins/packages/audioplayers/example/integration_test/audioplayers_test.dart line 122
The test description was:
do not exceed duration after audio completed
════════════════════════════════════════════════════════════════════════════════════════════════════

00:43 +4 -1: asset audio do not exceed duration after audio completed [E]
```

If this is a known issue and is currently not solvable, we should state that in the **Device Limitation** in README.

**Comment by XuWanchaoS** [comment]
The audioplayers plugin is implemented by mmplayer, it has some limitations on TV as video player plugin.
I add limitations in README. Integration test can work well on mobile/wearable.
https://github.com/flutter-tizen/plugins/pull/242
