### ISSUE TITLE
Hot restart is not working

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#341]
Federated plugins (including both Dart and native) fall back to their default Linux implementation when `Shift`+`R` is pressed in debug mode.

Example (`connectivity_plus_tizen`):
```
Syncing files to device Tizen M-6.0-x86...                          94ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Tizen M-6.0-x86 is available at: http://127.0.0.1:42053/o41EblQ8PBg=/
The Flutter DevTools debugger and profiler on Tizen M-6.0-x86 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:42053/o41EblQ8PBg=/

Performing hot restart...
Restarted application in 585ms.
[E] [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1122:13)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:628:12)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:83:18)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351:19)
<asynchronous suspension>
#4      ConnectivityLinux.checkConnectivity (package:connectivity_plus_linux/src/connectivity.dart:24:5)
<asynchronous suspension>
#5      _MyHomePageState.initConnectivity (package:connectivity_plus_example/main.dart:68:16)
<asynchronous suspension>
```

**Comment by swift-kim** [comment]
The problem is due to a conflict with the original flutter_tool's plugin system (the `.dart_tool/flutter_build/generated_main.dart` file created by `generateMainDartWithPluginRegistrant` is re-compiled during incremental build). I tried several ways (such as ignoring all `DartPluginRegistrantTarget`s by extending the `BuildSystem` class) to solve the problem but couldn't find a clean working solution. We might need to deprecate and remove support for Dart plugins completely.
