### ISSUE TITLE
[tizen_bundle] Bundle creation issue

### ISSUE THREAD

**Issue by JSUYA** [flutter-tizen/plugins#637]
When creating a bundle, an assertion is occured in calling _finaliser.attach().
(https://github.com/flutter-tizen/plugins/actions/runs/7139685481/job/19497841519)
```
2023-12-11T02:19:35.3050863Z ##[group]❌ can create a bundle (failed)
2023-12-11T02:19:35.3052247Z ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
2023-12-11T02:19:35.3053538Z The following assertion was thrown running a test:
2023-12-11T02:19:35.3054501Z The token should not be the value being attached
2023-12-11T02:19:35.3055404Z 'dart:core-patch/finalizer_patch.dart':
2023-12-11T02:19:35.3056592Z Failed assertion: line 41 pos 12: '<optimized out>'
2023-12-11T02:19:35.3057138Z 
2023-12-11T02:19:35.3057449Z When the exception was thrown, this was the stack:
2023-12-11T02:19:35.3058845Z #2      _FinalizerImpl.attach (dart:core-patch/finalizer_patch.dart:41:12)
2023-12-11T02:19:35.3059766Z #3      new Bundle (package:tizen_bundle/tizen_bundle.dart:23:16)
2023-12-11T02:19:35.3061366Z #4      main.<anonymous closure> (file:///home/tizen/runners/runner1/_work/plugins/plugins/packages/tizen_bundle/example/integration_test/bundle_test.dart:13:27)
2023-12-11T02:19:35.3063714Z #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:29)
2023-12-11T02:19:35.3064803Z <asynchronous suspension>
2023-12-11T02:19:35.3065340Z #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
2023-12-11T02:19:35.3066356Z <asynchronous suspension>
2023-12-11T02:19:35.3066645Z <asynchronous suspension>
2023-12-11T02:19:35.3067269Z (elided 3 frames from class _AssertionError and package:stack_trace)
```

I guess it's probably related to this issue.

https://github.com/dart-lang/sdk/commit/ea8485e967ecd1ac796832161ba853aee4eb085e

**Comment by swift-kim** [comment]
The finalizers are being misused in `tizen_bundle` and `tizen_rpc_port`.

c.f. https://github.com/flutter-tizen/plugins/blob/e86f535b833fded366d27d81f9002d12855e72e0/packages/tizen_app_manager/lib/src/app_manager.dart#L168

A simple fix should be something like this:

```patch
@@ -20,20 +20,20 @@ class Bundle extends MapMixin<String, Object> {
   /// Creates an empty [Bundle].
   Bundle() {
     _handle = tizen.bundle_create();
-    _finalizer.attach(this, this, detach: this);
+    _finalizer.attach(this, _handle, detach: this);
   }
@@ -44,8 +44,9 @@ class Bundle extends MapMixin<String, Object> {
   }

   late final Pointer<bundle> _handle;
-  static final Finalizer<Bundle> _finalizer =
-      Finalizer<Bundle>((Bundle bundle) => tizen.bundle_free(bundle._handle));
+  static final Finalizer<Pointer<bundle>> _finalizer =
+      Finalizer<Pointer<bundle>>(
+          (Pointer<bundle> bundle) => tizen.bundle_free(bundle));

   static final List<String> _keys = <String>[];
```

**Comment by JSUYA** [comment]
Thank you for your comment.
I applied your comment to RP. 
However, I couldn't think of an appropriate way in rpc_port case, so I wrapped it in a map.
I don't know if this is appropriate. If there is a good way, please let me know.
