### ISSUE TITLE
[video_player_avplay] Failed to build video_player_avplay plugin

### ISSUE THREAD

**Issue by Escaper-Park** [flutter-tizen/plugins#668]
I couldn't build an app when I tried to add video_player_avplay in Emulator and TV.

How can I solve this problem?

> flutter-tizen clean
> flutter-tizen pub get
> flutter-tizen run

## Error messages
```
target: tizen_native_plugins
exception:Exception: Failed to build video_player_avplay plugin:
[PLATFORM] Tizen-6.0
[ARCHITECTURE] i586
[COMPILER] LLVM-10.0
[CONFIGURATION] Debug
[SBI] prdefine options = -DTV_PROFILE
[SBI] command : cmd /c make.exe -f "C:\tizen-studio\tools\ide\resources\native\Build\makefile" 
-r
make -f C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: Entering directory       
'/c/Users/BGPark/AppData/Local/Pub/Cache/hosted/pub.dev/video_player_avplay-0.3.3/tizen'       
preparing to build src/drm_license_helper.cc
preparing to build src/drm_manager.cc
preparing to build src/drm_manager_proxy.cc
preparing to build src/ecore_wl2_window_proxy.cc
preparing to build src/media_player.cc
preparing to build src/media_player_proxy.cc
preparing to build src/messages.cc
preparing to build src/plus_player.cc
preparing to build src/video_player.cc
preparing to build src/video_player_tizen_plugin.cc
C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:164: warning: overriding recipe   
for target 'Debug'
C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:161: warning: ignoring old recipe 
for target 'Debug'
  Building file: src/drm_license_helper.cc
  Output Path ./Debug
  Invoking: C++ Compiler
  Building directory: Debug/src
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/drm_license_helper.cc" -o "Debug/src/drm_license_helper.o" -DTIZEN_DEPRECATION
-DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch"-g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi       
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/"    
-ccc-gcc-name i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
  Finished building: src/drm_license_helper.cc
  Building file: src/drm_manager.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/drm_manager.cc" -o "Debug/src/drm_manager.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING    
-DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0     
-Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name     
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
  Finished building: src/drm_manager.cc
  Building file: src/drm_manager_proxy.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/drm_manager_proxy.cc" -o "Debug/src/drm_manager_proxy.o" -DTIZEN_DEPRECATION
-DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch"-g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi       
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/"    
-ccc-gcc-name i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
  Finished building: src/drm_manager_proxy.cc
  Building file: src/ecore_wl2_window_proxy.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/ecore_wl2_window_proxy.cc" -o "Debug/src/ecore_wl2_window_proxy.o" -DTIZEN_DEPRECATION    
-DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch"-g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi       
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/"    
-ccc-gcc-name i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
  Finished building: src/ecore_wl2_window_proxy.cc
  Building file: src/media_player.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/media_player.cc" -o "Debug/src/media_player.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING  
-DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0     
-Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name     
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
In file included from src/media_player.cc:5:
In file included from src/media_player.h:16:
src/video_player.h:93:10: warning: local variable 'default_value' will be copied despite being 
returned by name [-Wreturn-std-move]
  return default_value;
         ^~~~~~~~~~~~~
src/media_player.cc:91:42: note: in instantiation of function template specialization
'flutter_common::GetValue<std::__cxx11::basic_string<char> >' requested here
    std::string cookie = flutter_common::GetValue(create_message.http_headers(),
                                         ^
src/video_player.h:93:10: note: call 'std::move' explicitly to avoid copying
  return default_value;
         ^~~~~~~~~~~~~
         std::move(default_value)
1 warning generated.
  Finished building: src/media_player.cc
  Building file: src/media_player_proxy.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/media_player_proxy.cc" -o "Debug/src/media_player_proxy.o" -DTIZEN_DEPRECATION
-DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch"-g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi       
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/"    
-ccc-gcc-name i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
  Finished building: src/media_player_proxy.cc
  Building file: src/messages.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/messages.cc"  
-o "Debug/src/messages.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE
-DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c
-fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name     
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
  Finished building: src/messages.cc
  Building file: src/plus_player.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/plus_player.cc" -o "Debug/src/plus_player.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING    
-DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0     
-Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name     
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
In file included from src/plus_player.cc:5:
In file included from src/plus_player.h:15:
inc\plusplayer/plusplayer_wrapper.h:471:32: warning: 'GetTrackLanguageCode' has C-linkage      
specified, but returns user-defined type 'std::string' (aka 'basic_string<char>') which is     
incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::string GetTrackLanguageCode(PlusplayerRef player,
                               ^
inc\plusplayer/plusplayer_wrapper.h:478:51: warning: 'GetTrackInfo' has C-linkage specified,   
but returns incomplete type 'std::vector<plusplayer::Track>' which could be incompatible with C[-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::vector<plusplayer::Track> GetTrackInfo(
                                                  ^
inc\plusplayer/plusplayer_wrapper.h:481:51: warning: 'GetActiveTrackInfo' has C-linkage        
specified, but returns incomplete type 'std::vector<plusplayer::Track>' which could be
incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::vector<plusplayer::Track> GetActiveTrackInfo(
                                                  ^
inc\plusplayer/plusplayer_wrapper.h:507:32: warning: 'GetStreamingProperty' has C-linkage      
specified, but returns user-defined type 'std::string' (aka 'basic_string<char>') which is     
incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::string GetStreamingProperty(PlusplayerRef player,
                               ^
src/plus_player.cc:34:1: warning: non-void function does not return a value in all control     
paths [-Wreturn-type]
}
^
In file included from src/plus_player.cc:5:
In file included from src/plus_player.h:16:
src/video_player.h:93:10: warning: local variable 'default_value' will be copied despite being 
returned by name [-Wreturn-std-move]
  return default_value;
         ^~~~~~~~~~~~~
src/plus_player.cc:86:42: note: in instantiation of function template specialization
'flutter_common::GetValue<std::__cxx11::basic_string<char> >' requested here
    std::string cookie = flutter_common::GetValue(create_message.http_headers(),
                                         ^
src/video_player.h:93:10: note: call 'std::move' explicitly to avoid copying
  return default_value;
         ^~~~~~~~~~~~~
         std::move(default_value)
6 warnings generated.
  Finished building: src/plus_player.cc
  Building file: src/video_player.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/video_player.cc" -o "Debug/src/video_player.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING  
-DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0     
-Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name     
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
  Finished building: src/video_player.cc
  Building file: src/video_player_tizen_plugin.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c
"src/video_player_tizen_plugin.cc" -o "Debug/src/video_player_tizen_plugin.o"
-DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc      
-Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target      
i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name     
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong
-Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-Werror-implicit-function-declaration  -std=c++17
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a" -Wp,@./Debug/objs/platform_incs_file.inc     
In file included from src/video_player_tizen_plugin.cc:20:
In file included from src/plus_player.h:15:
inc\plusplayer/plusplayer_wrapper.h:471:32: warning: 'GetTrackLanguageCode' has C-linkage      
specified, but returns user-defined type 'std::string' (aka 'basic_string<char>') which is     
incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::string GetTrackLanguageCode(PlusplayerRef player,
                               ^
inc\plusplayer/plusplayer_wrapper.h:478:51: warning: 'GetTrackInfo' has C-linkage specified,   
but returns incomplete type 'std::vector<plusplayer::Track>' which could be incompatible with C[-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::vector<plusplayer::Track> GetTrackInfo(
                                                  ^
inc\plusplayer/plusplayer_wrapper.h:481:51: warning: 'GetActiveTrackInfo' has C-linkage        
specified, but returns incomplete type 'std::vector<plusplayer::Track>' which could be
incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::vector<plusplayer::Track> GetActiveTrackInfo(
                                                  ^
inc\plusplayer/plusplayer_wrapper.h:507:32: warning: 'GetStreamingProperty' has C-linkage      
specified, but returns user-defined type 'std::string' (aka 'basic_string<char>') which is     
incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::string GetStreamingProperty(PlusplayerRef player,
                               ^
4 warnings generated.
  Finished building: src/video_player_tizen_plugin.cc
  Building target: Debug/libvideo_player_tizen_plugin.so
  Invoking: C/C++ Linker
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -o
./Debug/libvideo_player_tizen_plugin.so @./Debug/target_objs.file  -lplusplayer-wrapper        
-lgstsubtitle_tvplus -lgstsubtitleparse_tvplus -lplusplayercore_tvplus -ltracksource_tvplus    
-lplusplayer_tvplus -ldashplusplayer_tvplus -Llib/i586/6.0
-L"C:/Users/BGPark/AppData/Local/Pub/Cache/hosted/pub.dev/video_player_avplay-0.3.3/tizen/lib" 
-Wl,--no-undefined  -Wl,-rpath='$ORIGIN' -target i586-tizen-linux-gnueabi -gcc-toolchain       
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name     
i586-linux-gnueabi-g++ -march=i586 -Wl,-z,relro,--as-needed,-z,noseparate-code  -Xlinker       
--as-needed -shared -lpthread
--sysroot="C:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core" 
-LC:/tizen-studio/platforms/tizen-6.0/wearable/rootstraps/wearable-6.0-emulator.core/usr/lib   
@./Debug/platform_libs.file
-I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include" -I"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/c/dev/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/c/dev/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/5.5"
"/c/Users/BGPark/Desktop/Works/Tizen/Tester/tester/.dart_tool/flutter_build/c9912bf1a7cbd623e6d3e4e268c1fb86/tizen_embedding/libembedding_cpp.a"
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld: cannot find -lplusplayer-wrapperC:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld: cannot find -lgstsubtitle_tvplusC:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld: cannot find
-lgstsubtitleparse_tvplus
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld: cannot find
-lplusplayercore_tvplus
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld: cannot find -ltracksource_tvplusC:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld: cannot find -lplusplayer_tvplus 
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld: cannot find
-ldashplusplayer_tvplus
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: ***
[C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:155:
Debug/libvideo_player_tizen_plugin.so] Error 1
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: Leaving directory        
'/c/Users/BGPark/AppData/Local/Pub/Cache/hosted/pub.dev/video_player_avplay-0.3.3/tizen'       
make: *** [C:\tizen-studio\tools\ide\resources\native\Build\makefile:27: app_build] Error 2    
Total time: 00:00:26.466
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      NativePlugins.build (package:flutter_tizen/build_targets/plugins.dart:151:9)
<asynchronous suspension>
#2      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#4      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#6      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#7      FlutterBuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#8      TizenBuilder.buildTpk (package:flutter_tizen/tizen_builder.dart:103:11)
<asynchronous suspension>
#9      TizenDevice.startApp (package:flutter_tizen/tizen_device.dart:352:7)
<asynchronous suspension>
#10     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:477:33)
<asynchronous suspension>
#11     HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart:426:14)      
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#13     HotRunner.run (package:flutter_tools/src/run_hot.dart:443:34)
<asynchronous suspension>
#14     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:745:27)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)<asynchronous suspension>
#20     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)  
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)<asynchronous suspension>
#23     main (package:flutter_tizen/executable.dart:84:3)
<asynchronous suspension>
```

## tizen-manifest.xml
```
<?xml version="1.0" encoding="utf-8"?>
<manifest package="com.example.tester" version="1.0.0" api-version="6.0" xmlns="http://tizen.org/ns/packages">
    <profile name="tv"/>
    <ui-application appid="com.example.tester" exec="Runner.dll" type="dotnet" multiple="false" nodisplay="false" taskmanage="true">
        <label>tester</label>
        <icon>ic_launcher.png</icon>
        <metadata key="http://tizen.org/metadata/prefer_dotnet_aot" value="true"/>
    </ui-application>
    <feature name="http://tizen.org/feature/screen.size.all"/>
    <privileges>
        <privilege>http://tizen.org/privilege/mediastorage</privilege>
        <privilege>http://tizen.org/privilege/externalstorage</privilege>
        <privilege>http://tizen.org/privilege/internet</privilege>
        <privilege>http://developer.samsung.com/privilege/drmplay</privilege>
    </privileges>
</manifest>
```

**Comment by JSUYA** [comment]
Hi @Escaper-Park 
The video_player_avplay plugin does not run on the emulator. Could you please try targeting your tizen TV device?
​
Hi @xiaowei-guan 
plus_player.so in video_player_avplay is not ready for i586. Could you please edit the readme guide? Or can you support emulator?

**Comment by Escaper-Park** [comment]
Thank you @JSUYA . 

I wrote in my question that it doesn't work on Emulator and 'TV', but I think I made a mistake when targeting devices. It can build on TV.
