### ISSUE TITLE
[video_player] Its example crashes on Tizen 9.0

### ISSUE THREAD

**Issue by seungsoo47** [flutter-tizen/plugins#787]
* Environment
: Device - RPI5
: Build - tizen-9.0-unified_20241125.125444_tizen-headed-aarch64

1. Video_player's example is sometimes crashed.

2. I saw another error log in ConsoleMessage:
```
[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(player_set_playback_rate failed, Function not implemented, null, null)
#0      TizenVideoPlayerApi.setPlaybackSpeed (package:video_player_tizen/src/messages.g.dart:416:7)
<asynchronous suspension>
[E] #1      VideoPlayerController._applyPlaybackSpeed (package:video_player/video_player.dart:633:5)
<asynchronous suspension>
#2      VideoPlayerController._applyPlayPause (package:video_player/video_player.dart:607:7)
<asynchronous suspension>
#3      VideoPlayerController.play (package:video_player/video_player.dart:558:5)
<asynchronous suspension>

```

**Comment by Senne021** [comment]
I've got the same issue for live streams. The `play` method [sets the play back speed](https://github.com/flutter/packages/blob/f73cb00e127b3036e5b0459cff8c416fabcfd120/packages/video_player/video_player/lib/video_player.dart#L607) and this executes the native method [player_set_playback_rate](https://github.com/flutter-tizen/plugins/blob/af9f4a31c4f24aa286467fe957cd332b801da012/packages/video_player/tizen/src/video_player.cc#L357) which seems to be not implemented (or at least throws this exception in this case).

**Comment by xiaowei-guan** [comment]
I can reproduce this issue, It maybe need checked by MM team.

**Comment by xiaowei-guan** [comment]
> [@xiaowei-guan](https://github.com/xiaowei-guan) Are there any updates to this?

I can reproduce this issue on Tizen 9.0 with RPI4.  I think need to check this issue with MM team.  Is this issue a urgent issue?
if yes, I will check it as soon as possible.

**Comment by Senne021** [comment]
Yes, that is urgent. We have currently copied the video player from the [video_player_package](https://pub.dev/packages/video_player) into our codebase and removed the parts that are causing errors. However, this can have unwanted side effects, especially when updating the video player, which can lead to other problems.

**Comment by xiaowei-guan** [comment]
> Yes, that is urgent. We have currently copied the video player from the [video_player_package](https://pub.dev/packages/video_player) into our codebase and removed the parts that are causing errors. However, this can have unwanted side effects, especially when updating the video player, which can lead to other problems.

@Senne021 Do you get this issue on RPI5 or TV ?

**Comment by Senne021** [comment]
On TV

**Comment by xiaowei-guan** [comment]
> On TV

This issue was reproted on a RPI5 device, could you please create a new issue and share the test URL, I will check it on TV device.
