### ISSUE TITLE
[flutter_tts] PlatformException (Invalid Operation) when play has been canceled

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#87]
How to reproduce:

1. Launch the example app. (I used a TV 6.0 emulator.)
2. Enter some text in the text field and click PLAY, and then click STOP or PAUSE while the audio is playing.
3. Click PLAY again and see this error message:

```
I/ConsoleMessage(11739): flutter: Playing
I/ConsoleMessage(11739): flutter: Cancel
E/ConsoleMessage(11739): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(Invalid Operation, Invalid Operation, null, null)
E/ConsoleMessage(11739): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/ConsoleMessage(11739): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/ConsoleMessage(11739): <asynchronous suspension>
E/ConsoleMessage(11739): #2      _MyAppState._speak (package:flutter_tts_tizen_example/main.dart:90:9)
E/ConsoleMessage(11739): <asynchronous suspension>
```

cc @rookiejava @flutter-tizen/maintainers

**Comment by rookiejava** [comment]
Which binary did you test with? I couldn't reproduced on mobile emulator.
When it comes TV profile, as mentioned in the PR, I couldn't check on the  emulator. But when I checked it on the real target, I couldn't reproduce it. Test binary I tested is as follows.
```
Model=Tizen6/TV;
Build=latest;
Release=latest;
[Build]
Type=eng;
Date=20201111_193150;
Time=19:31:50;
Variant=NONE;
```

It may be a binary issue or a platform issue.

**Comment by swift-kim** [comment]
@rookiejava I tested on various devices (R800/TM1/TV emulator) and they all have the same issue. Here is the full log:

```
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : getLanguages
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : stop
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: OnStateChanged(259) > [TTS] State is changed (1) to (1)
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : setSpeechRate
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : awaitSpeakCompletion
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : speak
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: OnStateChanged(259) > [TTS] State is changed (1) to (2)
I/ConsoleMessage(32517): flutter: Playing
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : getLanguages
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : stop
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: OnStateChanged(259) > [TTS] State is changed (2) to (1)
I/ConsoleMessage(32517): flutter: Cancel
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : getLanguages
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : setSpeechRate
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : awaitSpeakCompletion
I/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(152) > method : speak
E/FlutterTtsTizenPlugin(32517): /home/swift/Git/flutter/plugins/packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc: HandleMethodCall(167) > [TTS] : You cannot speak again while speaking.
E/ConsoleMessage(32517): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(Invalid Operation, Invalid Operation, null, null)
E/ConsoleMessage(32517): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
E/ConsoleMessage(32517): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/ConsoleMessage(32517): <asynchronous suspension>
E/ConsoleMessage(32517): #2      _MyAppState._speak (package:flutter_tts_tizen_example/main.dart:90)
E/ConsoleMessage(32517): <asynchronous suspension>
E/ConsoleMessage(32517):
```

Maybe the `m_speaking` value is not being updated properly when `stop` or `pause` is received.

**Comment by rookiejava** [comment]
Ok. I'll check again. But tell me exactly what binary you tested.

**Comment by rookiejava** [comment]
Ah, you're saying that the app doesn't terminated abnormally, but there's an error. Anyway, let me check again.

**Comment by swift-kim** [comment]
The important part is the second step. I clicked the STOP (PAUSE) button **before speaking ended**.

**Comment by swift-kim** [comment]
Note: The change hasn't been published on pub.dev.
